
import { Inter } from 'next/font/google'
import './globals.css'
import NavDrawer from '@/components/nav-drawer'
import dataList from '../assets/data.json'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DMMA',
  description: 'Generated by Andr3w',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavDrawer dataList={dataList}/>
        {children}
      </body>
    </html>
  )
}
