
import { Inter } from 'next/font/google'
import './globals.css'
import NavDrawer from '@/components/nav-drawer'
import dataList from '../assets/data.json'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DMMA',
  description: 'Generated by Andr3w',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavDrawer dataList={dataList}/>
        {children}
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/6737984f2480f5b4f59ec10f/1id83c21m';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
      </body>
    </html>
  )
}
